# Last updated: 8/24/2026, 4:15:10 PM
1class Solution:
2    def isSymmetric(self, root: Optional[TreeNode]) -> bool:
3        # Special case...
4        if not root:
5            return true;
6        # Return the function recursively...
7        return self.isSame(root.left, root.right)
8    # A tree is called symmetric if the left subtree must be a mirror reflection of the right subtree...
9    def isSame(self, leftroot, rightroot):
10        # If both root nodes are null pointers, return true...
11        if leftroot == None and rightroot == None:
12            return True
13        # If exactly one of them is a null node, return false...
14        if leftroot == None or rightroot == None:
15            return False
16        # If root nodes haven't same value, return false...
17        if leftroot.val != rightroot.val:
18            return False
19        # Return true if the values of root nodes are same and left as well as right subtrees are symmetric...
20        return self.isSame(leftroot.left, rightroot.right) and self.isSame(leftroot.right, rightroot.left)